name: Cycling UK application
type: module
description: Provides Cycling UK applications based on Webform with a Dynamics integration.
package: Cycling UK
version: '1.10.1'
core_version_requirement: ^10 || ^11
dependencies:
  - drupal:webform
  - cycling_uk_application:cycling_uk_application_type
  - cycling_uk_application:cycling_uk_application_process
  - cycling_uk_application:cycling_uk_dynamics
