name: Cycling UK application type
type: module
description: 'Provides a cycling uk application type entity.'
package: Cycling UK
core_version_requirement: ^10 || ^11
dependencies:
  - drupal:text
configure: entity.cycling_uk_application_type.settings
